/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "admin.diet-plans.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.diet-plans.form": [
        {
            "name": "id",
            "required": false
        }
    ],
    "admin.diet-plans.list": [],
    "admin.diet-plans.store": [],
    "admin.diet-plans.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.trainers.form": [
        {
            "name": "id",
            "required": false
        }
    ],
    "admin.trainers.list": [],
    "admin.workout-classes.store": [],
    "home": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
